vehicles:
    rabittank:
        id: rabittank
        name: rabit tank
        width: 64
        height: 64
        hp: 300
        damage: 100
        radius: 15
        image: rabittank.svg
    ramtank:
        id: ramtank
        name: mutton tank
        width: 80
        height: 80
        hp: 300
        damage: 100
        radius: 50
        image: ramtank.svg
    elktank:
        id: elktank
        name: elk tank
        width: 100
        height: 100
        hp: 400
        damage: 200
        radius: 20
        image: elktank.svg
    foXtank:
        id: foxtank
        name: fox tank
        width: 100
        height: 100
        hp: 300
        damage: 100
        radius: 80
        image: foxtank.svg
